# This is a basic workflow to help you get started with Actions

name: pytest and flake8

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} # Name of an action that sets up Python.
        uses: actions/setup-python@v2 # A pre-built GitHub Action that sets up a Python environment.
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Install dependencies # The first step that isn't just calling another action.
        run: |
          python -m pip install --upgrade pip
          pip install pytest # Install pytest.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # If we have a requirements.txt, then install it.

      - name: Test with pytest # Final action which runs pytest. If any test fails, then this Action fails.
        run: |
          pytest
